const followingArtists = [
  {
    external_urls: {
      spotify: "https://open.spotify.com/artist/22RISwgVJyZu9lpqAcv1F5",
    },
    followers: {
      href: null,
      total: 424521,
    },
    genres: ["english indie rock", "modern rock"],
    href: "https://api.spotify.com/v1/artists/22RISwgVJyZu9lpqAcv1F5",
    id: "22RISwgVJyZu9lpqAcv1F5",
    images: [
      {
        height: 640,
        url: "https://i.scdn.co/image/ab6761610000e5eb66a7a2c4937d3170f6e6a8dc",
        width: 640,
      },
      {
        height: 320,
        url: "https://i.scdn.co/image/ab6761610000517466a7a2c4937d3170f6e6a8dc",
        width: 320,
      },
      {
        height: 160,
        url: "https://i.scdn.co/image/ab6761610000f17866a7a2c4937d3170f6e6a8dc",
        width: 160,
      },
    ],
    name: "Blossoms",
    popularity: 56,
    type: "artist",
    uri: "spotify:artist:22RISwgVJyZu9lpqAcv1F5",
  },
];

const userProfileDetails = {
  country: "GB",
  display_name: "yurek",
  email: "boguckiyurek@gmail.com",
  explicit_content: {
    filter_enabled: false,
    filter_locked: false,
  },
  external_urls: {
    spotify: "https://open.spotify.com/user/yurekb",
  },
  followers: {
    href: null,
    total: 4,
  },
  href: "https://api.spotify.com/v1/users/yurekb",
  id: "yurekb",
  images: [],
  product: "premium",
  type: "user",
  uri: "spotify:user:yurekb",
};

const userTopTracks = [
  {
    album: {
      album_type: "ALBUM",
      artists: [
        {
          external_urls: {
            spotify: "https://open.spotify.com/artist/21UJ7PRWb3Etgsu99f8yo8",
          },
          href: "https://api.spotify.com/v1/artists/21UJ7PRWb3Etgsu99f8yo8",
          id: "21UJ7PRWb3Etgsu99f8yo8",
          name: "Stereophonics",
          type: "artist",
          uri: "spotify:artist:21UJ7PRWb3Etgsu99f8yo8",
        },
      ],
      available_markets: [
        "AD",
        "AE",
        "AR",
        "AT",
        "AU",
        "BE",
        "BG",
        "BH",
        "BO",
        "BR",
        "CA",
        "CH",
        "CL",
        "CO",
        "CR",
        "CY",
        "CZ",
        "DE",
        "DK",
        "DO",
        "DZ",
        "EC",
        "EE",
        "EG",
        "ES",
        "FI",
        "FR",
        "GB",
        "GR",
        "GT",
        "HK",
        "HN",
        "HU",
        "ID",
        "IE",
        "IL",
        "IN",
        "IS",
        "IT",
        "JO",
        "JP",
        "KW",
        "LB",
        "LI",
        "LT",
        "LU",
        "LV",
        "MA",
        "MC",
        "MT",
        "MX",
        "MY",
        "NI",
        "NL",
        "NO",
        "NZ",
        "OM",
        "PA",
        "PE",
        "PH",
        "PL",
        "PS",
        "PT",
        "PY",
        "QA",
        "RO",
        "SA",
        "SE",
        "SG",
        "SK",
        "SV",
        "TH",
        "TN",
        "TR",
        "TW",
        "US",
        "UY",
        "VN",
        "ZA",
      ],
      external_urls: {
        spotify: "https://open.spotify.com/album/1DwcGY8AK9RS0IgmozyvyP",
      },
      href: "https://api.spotify.com/v1/albums/1DwcGY8AK9RS0IgmozyvyP",
      id: "1DwcGY8AK9RS0IgmozyvyP",
      images: [
        {
          height: 640,
          url: "https://i.scdn.co/image/ab67616d0000b273ecdb914ea9cbbb31c5a6b71b",
          width: 640,
        },
        {
          height: 300,
          url: "https://i.scdn.co/image/ab67616d00001e02ecdb914ea9cbbb31c5a6b71b",
          width: 300,
        },
        {
          height: 64,
          url: "https://i.scdn.co/image/ab67616d00004851ecdb914ea9cbbb31c5a6b71b",
          width: 64,
        },
      ],
      name: "Language.Sex.Violence.Other?",
      release_date: "2005-01-01",
      release_date_precision: "day",
      total_tracks: 11,
      type: "album",
      uri: "spotify:album:1DwcGY8AK9RS0IgmozyvyP",
    },
    artists: [
      {
        external_urls: {
          spotify: "https://open.spotify.com/artist/21UJ7PRWb3Etgsu99f8yo8",
        },
        href: "https://api.spotify.com/v1/artists/21UJ7PRWb3Etgsu99f8yo8",
        id: "21UJ7PRWb3Etgsu99f8yo8",
        name: "Stereophonics",
        type: "artist",
        uri: "spotify:artist:21UJ7PRWb3Etgsu99f8yo8",
      },
    ],
    available_markets: [
      "AD",
      "AE",
      "AR",
      "AT",
      "AU",
      "BE",
      "BG",
      "BH",
      "BO",
      "BR",
      "CA",
      "CH",
      "CL",
      "CO",
      "CR",
      "CY",
      "CZ",
      "DE",
      "DK",
      "DO",
      "DZ",
      "EC",
      "EE",
      "EG",
      "ES",
      "FI",
      "FR",
      "GB",
      "GR",
      "GT",
      "HK",
      "HN",
      "HU",
      "ID",
      "IE",
      "IL",
      "IN",
      "IS",
      "IT",
      "JO",
      "JP",
      "KW",
      "LB",
      "LI",
      "LT",
      "LU",
      "LV",
      "MA",
      "MC",
      "MT",
      "MX",
      "MY",
      "NI",
      "NL",
      "NO",
      "NZ",
      "OM",
      "PA",
      "PE",
      "PH",
      "PL",
      "PS",
      "PT",
      "PY",
      "QA",
      "RO",
      "SA",
      "SE",
      "SG",
      "SK",
      "SV",
      "TH",
      "TN",
      "TR",
      "TW",
      "US",
      "UY",
      "VN",
      "ZA",
    ],
    disc_number: 1,
    duration_ms: 297426,
    explicit: false,
    external_ids: {
      isrc: "GBBLK0500005",
    },
    external_urls: {
      spotify: "https://open.spotify.com/track/3qaSqrrevBrb84xl5JlptU",
    },
    href: "https://api.spotify.com/v1/tracks/3qaSqrrevBrb84xl5JlptU",
    id: "3qaSqrrevBrb84xl5JlptU",
    is_local: false,
    name: "Dakota",
    popularity: 71,
    preview_url:
      "https://p.scdn.co/mp3-preview/45a03d196e3366d2235b0ef2b81724529c0c4d80?cid=ce590e96797142d78a585cde9409f13a",
    track_number: 5,
    type: "track",
    uri: "spotify:track:3qaSqrrevBrb84xl5JlptU",
  },
];

const userTopArtists = [
  {
    external_urls: {
      spotify: "https://open.spotify.com/artist/22RISwgVJyZu9lpqAcv1F5",
    },
    followers: {
      href: null,
      total: 0,
    },
    genres: ["english indie rock", "modern rock"],
    href: "https://api.spotify.com/v1/artists/22RISwgVJyZu9lpqAcv1F5",
    id: "22RISwgVJyZu9lpqAcv1F5",
    images: [
      {
        height: 640,
        url: "https://i.scdn.co/image/ab6761610000e5eb66a7a2c4937d3170f6e6a8dc",
        width: 640,
      },
      {
        height: 320,
        url: "https://i.scdn.co/image/ab6761610000517466a7a2c4937d3170f6e6a8dc",
        width: 320,
      },
      {
        height: 160,
        url: "https://i.scdn.co/image/ab6761610000f17866a7a2c4937d3170f6e6a8dc",
        width: 160,
      },
    ],
    name: "Blossoms",
    popularity: 56,
    type: "artist",
    uri: "spotify:artist:22RISwgVJyZu9lpqAcv1F5",
  },
];
